// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReadingRoomManager.DB;

#nullable disable

namespace ReadingRoomManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251102060321_RoomModelChnagedLatest")]
    partial class RoomModelChnagedLatest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ReadingRoomManager.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "Start", "End");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            End = new DateTime(2025, 11, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 1,
                            Start = new DateTime(2025, 11, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            End = new DateTime(2025, 11, 2, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 2,
                            Start = new DateTime(2025, 11, 2, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        });
                });

            modelBuilder.Entity("ReadingRoomManager.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 4,
                            Name = "Room A"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 5,
                            Name = "Room B"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 2,
                            Name = "Room C"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 7,
                            Name = "Room D"
                        });
                });

            modelBuilder.Entity("ReadingRoomManager.Entities.Reservation", b =>
                {
                    b.HasOne("ReadingRoomManager.Entities.Room", "room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("room");
                });

            modelBuilder.Entity("ReadingRoomManager.Entities.Room", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
